App routing
cinchronicity/FlixHive-client pull request #4
Opened 2024-11-21 04:34 UTC by cinchronicity

2024-11-21 11:49 UTC, Stanley-Okwii requested changes
Hi @cinchronicity ,

You’re almost done with this! There are just a few things to fix, and once those are done, it’ll be ready for approval.

2024-11-21 11:49 UTC, Stanley-Okwii commented on src/components/main-view/main-view.jsx
> +                  // onUserDeregister={handleUserDeregister}
I don't believe you have defined the `handleUserDeregister` function, but you still use the `onUserDeregister` prop in the profile view component.  Please define it, and the idea was to clear the local storage after a user deregisters.

2024-11-21 11:49 UTC, Stanley-Okwii commented on src/components/main-view/main-view.jsx
> +                  // onUserDeregister={handleUserDeregister}
You can also reuse the already defined `handleLogout` function like this.
```suggestion
                  onUserDeregister={handleLogout}
```

2024-11-21 11:49 UTC, Stanley-Okwii commented on src/components/movie-view/movie-view.jsx
> +    });
This API call isn't used for anything in your code, please consider removing it.

2024-11-21 11:49 UTC, Stanley-Okwii commented on src/components/movie-view/movie-view.jsx
> +        console.log("Error removing movie from favorites", error);
Use `console.error`, it's better for easy identification in the browser console logs. Also update other instance to where you catch errors to use it.

2024-11-21 11:49 UTC, Stanley-Okwii commented on src/components/movie-view/movie-view.jsx
> +        console.log("Successfully removed from favorites:", response.data);
While `console.log` statements are useful for debugging, they shouldn’t be committed to production or deployed with your application. They only clutter your code. Adhering to a minimalistic approach in writing code involves only including the necessary code to achieve functionality. If a piece of code isn’t functional, it has no place in your codebase.

2024-11-21 11:49 UTC, Stanley-Okwii commented on src/components/movie-view/movie-view.jsx
> +  }, [movieId]); // Dependency on movieId ensures it's triggered on route change
Nice one 🎉

2024-11-21 11:49 UTC, Stanley-Okwii commented on src/components/profile-view/profile-view.jsx
> +    fetch(
Since you installed `axios` for making API calls, it best practice to be consistent and use it throughout your code.

2024-11-21 11:49 UTC, Stanley-Okwii commented on src/index.html
> +    <!-- <h2> Welcome to the FlixHive</h2> -->
You could also just delete it, instead of commenting it out.

2024-11-22 07:33 UTC, cinchronicity commented on src/components/main-view/main-view.jsx
> +                  // onUserDeregister={handleUserDeregister}
I would like some more clarification on this. Is my onUserUpdate or handleUserUpdate not necessary since they are not defined? 
I made the change you suggested   ``` onUserDeregister={handleLogout}```

2024-11-23 23:12 UTC, Stanley-Okwii commented on src/components/main-view/main-view.jsx
> +                  // onUserDeregister={handleUserDeregister}
@cinchronicity `handleUserUpdate` is defined, but it's not used after passing into the `ProfileView` Component. It's necessary but it's a function that you would call after successfully updating a users information to set the value values of emails or username to the state.

2024-11-27 05:24 UTC, merged